name: "Testing of the app"

on:
    push:
        branches:
            - release
    pull_request:
        branches:
            - release

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.2

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Get versions
              run: |
                  php --version
                  node --version
            
            - name: Install dependencies
              run: npm install && composer install
            
            - name: Run tests
              run: npm run test && php artisan test